---
repos:
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.2
      hooks:
          - id: yamlfmt
    - repo: https://github.com/psf/black
      rev: 22.6.0
      hooks:
          - id: black
            args: [--safe, --quiet]
            exclude: ^src/pycbf/_wrapper.py

    - repo: https://github.com/PyCQA/flake8
      rev: 5.0.4
      hooks:
          - id: flake8

    - repo: https://github.com/PyCQA/isort.git
      rev: 5.10.1
      hooks:
          - id: isort
            exclude: ^src/pycbf/_wrapper.py
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: no-commit-to-branch
