---
repos:
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.1.0
      hooks:
          - id: yamlfmt
    - repo: https://github.com/psf/black
      rev: 21.4b0
      hooks:
          - id: black
            args: [--safe, --quiet]

