---
repos:
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.1.0
      hooks:
          - id: yamlfmt
    - repo: https://github.com/psf/black
      rev: 21.4b0
      hooks:
          - id: black
            args: [--safe, --quiet]
            exclude: ^src/pycbf/_wrapper.py

    - repo: https://github.com/PyCQA/flake8
      rev: 3.9.1
      hooks:
          - id: flake8

    - repo: https://github.com/PyCQA/isort.git
      rev: 5.8.0
      hooks:
          - id: isort
            exclude: ^src/pycbf/_wrapper.py
