---
repos:
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.1
      hooks:
          - id: yamlfmt

    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.4.8
      hooks:
          - id: ruff
            args: [--fix, --exit-non-zero-on-fix, --show-fixes]
          - id: ruff-format

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.0
      hooks:
          - id: no-commit-to-branch
