[tool.poetry]
name = "pycbf"
version = "0.0.96"
description = ""
authors = ["Nicholas Devenish <ndevenish@gmail.com>"]
license = "LGPL-2.1-or-later"
build = "build.py"

[tool.poetry.dependencies]
python = ">=2.7"

[tool.poetry.dev-dependencies]
ninja = "^1.10.0"
cmake = [ { version="^3.18.4", markers= "platform_machine != 'arm64' " } ]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
exclude = "cbflib/|src/pycbf/__init__.py"

[tool.isort]
skip = [ "cbflib/", "setup.py", "src/pycbf/__init__.py"]
