---
name: Build

on: [push, pull_request]

jobs:
    build_wheels:
        name: Build wheels on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-20.04, macos-10.15]

        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: true
                  lfs: true
            - name: Build wheel
              uses: joerick/cibuildwheel@v1.11.0
              env:
                  CIBW_SKIP: cp2* cp35* pp27*
                  CIBW_BEFORE_BUILD: pip install Cython
                  CIBW_TEST_COMMAND: pytest {package}/tests
                  CIBW_BEFORE_TEST: pip install pytest

            # to supply options, put them in 'env', like:
            # env:
            #   CIBW_SOME_OPTION: value

            - uses: actions/upload-artifact@v2
              with:
                  path: ./wheelhouse/*.whl
