---
name: Build

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build_wheels:
        name: Build wheels on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-20.04, macos-10.15]

        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: true
            - name: Install dials-data
              run: |
                  pip3 install git+https://github.com/ndevenish/data@pycbf
                  dials.data get pycbf
            - name: Build wheel
              uses: joerick/cibuildwheel@v1.11.0
              env:
                  CIBW_SKIP: cp2* cp35* pp27*
                  CIBW_TEST_COMMAND: pytest --regression {package}/tests
                  CIBW_BEFORE_TEST: pip install pytest git+https://github.com/ndevenish/data@pycbf

            # to supply options, put them in 'env', like:
            # env:
            #   CIBW_SOME_OPTION: value

            - uses: actions/upload-artifact@v2
              with:
                  path: ./wheelhouse/*.whl
